<a href="https://colab.research.google.com/github/SilpaVV/Machine-learning/blob/main/linear_regression_multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Rhevathi/DATA-SCIENCE/master/ML/2_linear_reg_multivariate/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
df.bedrooms.median()

4.0

In [ ]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [ ]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict([[3000, 3, 40]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [ ]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

In [ ]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

53713.86 and 93747.79

In [ ]:
data=pd.read_csv('https://raw.githubusercontent.com/Rhevathi/DATA-SCIENCE/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [ ]:
data.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [ ]:
data.columns=data.columns.str.replace(' ','_')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out_of_10)       7 non-null      float64
 2   interview_score(out_of_10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [ ]:
data.isnull().sum()

experience                    2
test_score(out_of_10)         1
interview_score(out_of_10)    0
salary($)                     0
dtype: int64

In [ ]:
data

experience  test_score(out_of_10)  interview_score(out_of_10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
data['test_score(out_of_10)']=data['test_score(out_of_10)'].fillna(data['test_score(out_of_10)'].mean())

<ipython-input-44-3de101efc71c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['test_score(out_of_10)']=data['test_score(out_of_10)'].fillna(data['test_score(out_of_10)'].mean())


In [ ]:
data

experience  test_score(out_of_10)  interview_score(out_of_10)  salary($)
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    8.0                           7      72000
7         11                    7.0                           8      80000

In [ ]:
pip install word2number

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from word2number import w2n

In [ ]:
data=data.dropna()

In [ ]:
data

experience  test_score(out_of_10)  interview_score(out_of_10)  salary($)
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
for x in range(2,len(data['experience'])+2):
  data['experience'][x]=w2n.word_to_num(data['experience'][x])
data

<ipython-input-34-0542b8d8fd04>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['experience'][x]=w2n.word_to_num(data['experience'][x])


experience  test_score(out_of_10)  interview_score(out_of_10)  salary($)
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    8.0                           7      72000
7         11                    7.0                           8      80000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(data.drop('salary($)',axis='columns'),data['salary($)'])

LinearRegression()

In [ ]:
reg.predict([[2, 9, 6]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([56600.58029804])

In [ ]:
reg.predict([[12, 10, 10]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88585.79114905])

In [ ]:
import pickle

In [ ]:
with open('reg_pickle', 'wb') as f:
  pickle.dump(reg,f)

In [ ]:
with open('reg_pickle', 'rb') as f:
  sreg=pickle.load(f)

In [ ]:
sreg.predict([[2,3,5]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([44655.42691343])